### ISSUE TITLE
To get basic installation instructions in ReadMe

### ISSUE THREAD

**Issue by sami10007** [akerbos/ltx2any#80]
Dear Developer, 

I would like to get basic installation instructions here for OS X in your ReadMe. 

Your application is one proposal here http://tex.stackexchange.com/a/306060/13173. I would like to systematically test your application with TextMate if it can make the workflow smoother. I really like the approach of keeping auxiliary files in one location, instead of removing them all. 

Best regards, 

Masi

**Comment by reitzig** [comment]
Thank you for your interest!

There are no installation instructions for any platform yet. Beyond the basic process -- install Ruby, install LaTeX, put ltx2any somewhere, link the main executable from somewhere in the PATH -- I don't know what I should say. In particular, I can test only on GNU/Linux.

Does that help you? Otherwise you're on your own, I'm afraid, sorry. :/

**Comment by sami10007** [comment]
Of course, it helps. It is just the basic which any projects need to have. Please, add at least your description in the ReadMe with clear examples of the work process. You clearly know what to say. GNU/Linux is enough. I can test it then in OS X.

**Comment by koppor** [comment]
Refs #61

**Comment by akerbos** [comment]
@sami10007 [Done.](https://github.com/akerbos/ltx2any/wiki) Please let me know if I need to add anything for Mac.
