### ISSUE TITLE
Markdown format: Possible to make it GFM compatible?

### ISSUE THREAD

**Issue by koppor** [akerbos/ltx2any#90]
I am trying to use [grip](https://github.com/joeyespo/grip) to instantly render the `log.md` since PDF generation takes too long.

The generated markdown, however, doesn't seem to be fully GitHub-flavoured markdown compatible.

See following screenshot:

- generated markdown
- rendered html
- generated PDF (by ltx2any)

![grabbed_20170130-220304](https://cloud.githubusercontent.com/assets/1366654/22441502/ef0c79e2-e737-11e6-97ba-40279c781558.png)

Is it possible to make the markdown fully gfm-conformant?

- Putting links as `[filename.tex](filename.tex)`
- Right alignment by using `<div style="text-align: right"> your-text-here </div>` - or no right alignment at all - or putting the line of the log next to the warning.
  (source: http://stackoverflow.com/a/40438921/873282)
- no line breaks within words

**Comment by akerbos** [comment]
The Markdown logs were designed to be human-readable, not necessarily to be compiled. Using

    pandoc -f Markdown -S -s -o foo.log.html foo.log.md 

gives a decent result; alignment can't be done better using plain, readable Markdown.

I probably won't implement other log modes (except maybe a JSON output for use by editors); what I will do is create an abstraction for log writers so that it's easy (for others) to implement more.

<snark>If log compilation takes to long, you need to be writing cleaner LaTeX! :P</snark>

**Comment by akerbos** [comment]
With #92 implemented, it should be straight-forward to add more log formats. I'll be happy to review any pull requests!
That said, with #103 coming up custom post-processing routines (written in whatever language you want) are also a possibility.
